
baseURL = 'https://irumi1206.github.io/'
languageCode = 'en-us'
title = 'Sungha Kim'
theme = 'PaperMod'

disableKinds = ['home']

[params]
defaultTheme = 'light'
disableThemeToggle = true
ShowBreadCrumbs = false

[[menu.main]]
name = 'About'
url = '/about/'
weight = 10

[[menu.main]]
name = 'Projects'
url = '/projects/'
weight = 20

[[menu.main]]
name = 'Study'
url = '/study/'
weight = 30