baseURL = 'https://irumi1206.github.io/'
languageCode = 'en-us'
title = 'Sungha Kim'
theme = 'PaperMod'

disableKinds = ['home']

[params]
defaultTheme = 'light'
disableThemeToggle = true
ShowBreadCrumbs = true


[[menu.main]]
identifier = 'about'
name = 'About'
pageRef = '/about'
weight = 10

[[menu.main]]
identifier = 'projects'
name = 'Projects'
pageRef = '/projects'
weight = 20

[[menu.main]]
identifier = 'notes'
name = 'Notes'
pageRef = '/notes'
weight = 30